server:
  port: 8087

spring:
  application:
    name: compliance-service
  datasource:
    url: jdbc:mysql://localhost:3306/xdr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.xdr.compliance: debug
